name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # (옵션) Node가 필요하진 않지만, 추후 스크립트 대비
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Firebase Hosting 배포 액션
      - name: Deploy to Firebase Hosting (live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLAYSOUNDLIST }}
          projectId: playsoundlist-b6ba2
          channelId: live
